// features/vod/components/highlight/mock.ts
import type { ChapterSummaryData, SegmentSummaryData } from "./types";

export const MOCK_SEGMENTS: SegmentSummaryData[] = [
    {
        id: "broadcast-recap-seg-1",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-2",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-12",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-22",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-13",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-23",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-14",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-24",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-15",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-25",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-16",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-26",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-17",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-27",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-18",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-28",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
    {
        id: "broadcast-recap-seg-19",
        chapterId: "broadcast-recap-ch-1",
        startTime: 300000, // 00:02:05
        endTime: 600000,
        atmosphere: "Funny",
        summary: "침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면.침착맨이 삼국지 유비의 귀 큰 특징을 설명하며 역대급 비유를 시전하는 장면. 시청자들이 채팅창에서 폭발적인 반응을 보임.",
        keywords: ["유비", "귀큰놈", "폭소"],
        momentum: 15.2,
        volume: 1200,
        score: 9.5,
        volPeak: { timestamp: 360000, volume: 0.58, momentum: 2.12 },
        mmtPeak: { timestamp: 390000, volume: 0.33, momentum: 2.81 },
    },
    {
        id: "broadcast-recap-seg-29",
        chapterId: "broadcast-recap-ch-2",
        startTime: 4500000, // 00:07:30
        endTime: 4800000,
        atmosphere: "Tension",
        summary: "조조가 등장하며 분위기가 반전되는 순간. 배경음악과 함께 긴장감이 고조됨.",
        keywords: ["조조", "등장", "긴장감"],
        momentum: 8.5,
        volume: 800,
        score: 8.2,
        volPeak: { timestamp: 4620000, volume: 0.72, momentum: -1.12 },
        mmtPeak: { timestamp: 4650000, volume: 0.31, momentum: 3.34 },
    },
];

export const MOCK_CHAPTERS: ChapterSummaryData[] = [
    {
        id: "broadcast-recap-ch-1",
        title: "1부: 오프닝 및 근황 토크",
        summary: "방송 시작과 함께 한 주간의 근황을 나누고, 오늘 플레이할 삼국지 게임에 대한 기대감을 이야기하는 시간.",
        startTime: 0,
        endTime: 3600000, // 1시간
    },
    {
        id: "broadcast-recap-ch-2",
        title: "2부: 삼국지 유비 플레이 시작",
        summary: "본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.",
        startTime: 3600000,
        endTime: 7200000, // 2시간
    },
    {
        id: "broadcast-recap-ch-3",
        title: "1부: 오프닝 및 근황 토크",
        summary: "방송 시작과 함께 한 주간의 근황을 나누고, 오늘 플레이할 삼국지 게임에 대한 기대감을 이야기하는 시간.",
        startTime: 7200000,
        endTime: 10800000,
    },
    {
        id: "broadcast-recap-ch-4",
        title: "2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작",
        summary: "본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.",
        startTime: 10800000,
        endTime: 14400000,
    },
    {
        id: "broadcast-recap-ch-5",
        title: "1부: 오프닝 및 근황 토크",
        summary: "방송 시작과 함께 한 주간의 근황을 나누고, 오늘 플레이할 삼국지 게임에 대한 기대감을 이야기하는 시간.",
        startTime: 14400000,
        endTime: 18000000,
    },
    {
        id: "broadcast-recap-ch-6",
        title: "2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작",
        summary: "본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.",
        startTime: 18000000,
        endTime: 21600000,
    },
    {
        id: "broadcast-recap-ch-7",
        title: "1부: 오프닝 및 근황 토크",
        summary: "방송 시작과 함께 한 주간의 근황을 나누고, 오늘 플레이할 삼국지 게임에 대한 기대감을 이야기하는 시간.",
        startTime: 21600000,
        endTime: 25200000,
    },
    {
        id: "broadcast-recap-ch-8",
        title: "2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작2부: 삼국지 유비 플레이 시작",
        summary: "본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.본격적인 게임 시작. 유비 캐릭터를 생성하고 초반 시나리오를 진행하며 시청자들과 캐릭터 커스터마이징을 논의함.",
        startTime: 25200000,
        endTime: 28800000,
    },
];
