services:
  vod-context:
    container_name: vod-context
    image: vod-context
    volumes:
      - ./VODContext/whisperx_models:/app/whisperx_models
      - ./VODContext/data:/app/data
    stdin_open: true  # -i 옵션과 동일
    tty: true         # -t 옵션과 동일
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - ./VODContext/env.example
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  watcher:
    build:
      context: ./BroadcasterStatusWatcher
    container_name: broadcaster_watcher
    env_file:
      - ./BroadcasterStatusWatcher/.env
    networks:
      - app-network
    depends_on:
      - redis

volumes:
  redis-data:


networks:
  app-network:
    driver: bridge
