services:
  collector:
    build:
      context: .
      dockerfile: ./chatzzk/services/collector/Dockerfile
    container_name: chatzzk_collector

    # .env 파일의 정확한 경로를 명시
    env_file:
      - ./chatzzk/services/collector/.env
    # volumes:
    #   - ./chatzzk:/app/chatzzk
