services:
  test-db:
    image: postgres
    container_name: chatzzk-test-db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - "5433:5432" # 호스트의 5433 포트를 컨테이너의 5432 포트와 연결
    volumes:
      - test-db-data:/var/lib/postgresql/data

  test-minio:
    image: minio/minio
    container_name: chatzzk-test-minio
    environment:
      - MINIO_ROOT_USER=testadmin
      - MINIO_ROOT_PASSWORD=testsecret
    ports:
      - "9001:9000" # MinIO API 포트
      - "9091:9090" # MinIO Console 포트
    command: server /data --console-address ":9090"

  test-adminer:
    image: adminer
    # restart: always
    ports:
      - 8081:8080

volumes:
  test-db-data:
