[project]
name = "chatzzk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.2",
    "alembic>=1.17.2",
    "alembic-postgresql-enum>=1.8.0",
    "asyncpg>=0.30.0",
    "dependency-injector>=4.48.2",
    "ffmpeg-python>=0.2.0",
    "loguru>=0.7.3",
    "m3u8>=6.0.0",
    "orjson>=3.11.4",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.44",
    "tenacity>=9.1.2",
]

[project.optional-dependencies]
core = [
    "torch>=2.9.1",
]
ml-tools = [
    "numpy>=2.3.5",
    "onnxruntime>=1.23.2",
    "silero-vad>=6.2.0",
    "torchcodec>=0.8.1",
]
backend-tools = [
    "fastapi>=0.121.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
asr-server = [
    "whisperx>=3.4.3",
    "chatzzk[ml-tools]",
    "chatzzk[backend-tools]",
    "torch==2.8.0",
]

dev = [
    "chatzzk[core]",
    "chatzzk[ml-tools]",
    "chatzzk[backend-tools]",
    "pre-commit>=4.4.0",
    "ruff>=0.14.5",
]


[tool.uv]
conflicts = [
    [
      { extra = "asr-server" },
      { extra = "dev" },
      { extra = "core" },
    ],
]

[tool.ruff]
line-length = 120
target-version = "py311"
