[project]
name = "chatzzk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
all-dev = [
    "chatzzk-schemas[dev]",
    "chatzzk-constants",
    "chatzzk-data-access[dev]",
    "chatzzk-clients[dev]",
]

db-migration = [
    "alembic>=1.17.2",
    "alembic-postgresql-enum>=1.8.0",
    "psycopg2-binary>=2.9.11",
]

dev = [
    "dependency-injector>=4.48.2",
    "chatzzk[all-dev]",
    "chatzzk[db-migration]",
    "pre-commit>=4.4.0",
    "ruff>=0.14.5",
]

[tool.uv.sources]
"chatzzk-schemas" = { workspace = true }
"chatzzk-constants" = { workspace = true }
"chatzzk-data-access" = { workspace = true }
"chatzzk-clients" = { workspace = true }

[tool.uv.workspace]
members = [
    "chatzzk/packages/*",
    "chatzzk/services/asr_inference_server",
]

[tool.ruff]
line-length = 120
target-version = "py311"
