apiVersion: v1
kind: Service
metadata:
  name: postgres-service # 애플리케이션이 사용할 DNS 이름
spec:
  selector:
    app: postgres # 'app: postgres' 라벨이 붙은 Pod를 찾아서 연결
  ports:
    - protocol: TCP
      port: 5432       # 서비스가 노출할 포트
      targetPort: 5432 # Pod 내부 컨테이너의 포트
