apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080       # 서비스가 노출할 포트
      targetPort: 8080 # Adminer 컨테이너의 포트
  # type: ClusterIP (기본값) - 클러스터 내부에서만 접근 가능하도록 설정
