apiVersion: v1
kind: Service
metadata:
  name: asr-inference-service # Collector가 사용할 DNS 이름
spec:
  selector:
    app: asr-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
