apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster-watcher
  template:
    metadata:
      labels:
        app: broadcaster-watcher
    spec:
      containers:
      - name: watcher
        image: broadcaster-watcher  # 빌드 후 푸시한 이미지 사용
        envFrom:
        - configMapRef:
            name: watcher-config
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-watcher-service
spec:
  selector:
    app: broadcaster-watcher
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
data:
  WATCH_INTERVAL_SECONDS: "5"
  CHANNEL_IDS: "e9c11510c1c6097a20b92ebcb289b26a, c847a58a1599988f6154446c75366523, 4515b179f86b67b4981e16190817c580, b044e3a3b9259246bc92e863e7d3f3b8, bdc57cc4217173f0e89f63fba2f1c6e5"
  HEADERS_JSON: '{"User-Agent": ""}'
  REDIS_URL: "redis://redis-service:6379"
  CHZZK_LIVE_STATUS_STREAM: "chzzk_live_status_events"
