"""add_retry_count_to_processing_status

Revision ID: 055dd41b888b
Revises: 7c02192b91f7
Create Date: 2025-09-26 13:42:03.598046

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "055dd41b888b"
down_revision: str | Sequence[str] | None = "7c02192b91f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chzzk_vod_processing_status",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chzzk_vod_processing_status", "retry_count")
    # ### end Alembic commands ###
