"""add ondelete CASCADE for channel_id and vod_id

Revision ID: 23a3d3271cf2
Revises: c9061d007f44
Create Date: 2025-11-26 18:20:35.235201

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "23a3d3271cf2"
down_revision: Union[str, Sequence[str], None] = "c9061d007f44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("channel_llm_metadatas_channel_id_fkey"), "channel_llm_metadatas", type_="foreignkey")
    op.create_foreign_key(
        "channel_llm_metadatas_channel_id_fkey",
        "channel_llm_metadatas",
        "channels",
        ["channel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("channel_metadatas_channel_id_fkey"), "channel_metadatas", type_="foreignkey")
    op.create_foreign_key(
        "channel_metadatas_channel_id_fkey", "channel_metadatas", "channels", ["channel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("chzzk_channels_channel_id_fkey"), "chzzk_channels", type_="foreignkey")
    op.create_foreign_key(
        "chzzk_channels_channel_id_fkey", "chzzk_channels", "channels", ["channel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("chzzk_vod_asr_analytics_chzzk_vod_id_fkey"), "chzzk_vod_asr_analytics", type_="foreignkey")
    op.create_foreign_key(
        "chzzk_vod_asr_analytics_chzzk_vod_id_fkey",
        "chzzk_vod_asr_analytics",
        "chzzk_vods",
        ["chzzk_vod_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("chzzk_vod_chat_analytics_chzzk_vod_id_fkey"), "chzzk_vod_chat_analytics", type_="foreignkey"
    )
    op.create_foreign_key(
        "chzzk_vod_chat_analytics_chzzk_vod_id_fkey",
        "chzzk_vod_chat_analytics",
        "chzzk_vods",
        ["chzzk_vod_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("chzzk_vods_vod_id_fkey"), "chzzk_vods", type_="foreignkey")
    op.create_foreign_key("chzzk_vods_vod_id_fkey", "chzzk_vods", "vods", ["vod_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("result_object_keys_vod_id_fkey"), "result_object_keys", type_="foreignkey")
    op.create_foreign_key(
        "result_object_keys_vod_id_fkey", "result_object_keys", "vods", ["vod_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("vod_overall_processing_statuses_vod_id_fkey"), "vod_overall_processing_statuses", type_="foreignkey"
    )
    op.create_foreign_key(
        "vod_overall_processing_statuses_vod_id_fkey",
        "vod_overall_processing_statuses",
        "vods",
        ["vod_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("vod_processing_status_details_vod_id_fkey"), "vod_processing_status_details", type_="foreignkey"
    )
    op.create_foreign_key(
        "vod_processing_status_details_vod_id_fkey",
        "vod_processing_status_details",
        "vods",
        ["vod_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("vods_channel_id_fkey"), "vods", type_="foreignkey")
    op.create_foreign_key("vods_channel_id_fkey", "vods", "channels", ["channel_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vods_channel_id_fkey", "vods", type_="foreignkey")
    op.create_foreign_key(op.f("vods_channel_id_fkey"), "vods", "channels", ["channel_id"], ["id"])
    op.drop_constraint("vod_processing_status_details_vod_id_fkey", "vod_processing_status_details", type_="foreignkey")
    op.create_foreign_key(
        op.f("vod_processing_status_details_vod_id_fkey"), "vod_processing_status_details", "vods", ["vod_id"], ["id"]
    )
    op.drop_constraint(
        "vod_overall_processing_statuses_vod_id_fkey", "vod_overall_processing_statuses", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("vod_overall_processing_statuses_vod_id_fkey"),
        "vod_overall_processing_statuses",
        "vods",
        ["vod_id"],
        ["id"],
    )
    op.drop_constraint("result_object_keys_vod_id_fkey", "result_object_keys", type_="foreignkey")
    op.create_foreign_key(op.f("result_object_keys_vod_id_fkey"), "result_object_keys", "vods", ["vod_id"], ["id"])
    op.drop_constraint("chzzk_vods_vod_id_fkey", "chzzk_vods", type_="foreignkey")
    op.create_foreign_key(op.f("chzzk_vods_vod_id_fkey"), "chzzk_vods", "vods", ["vod_id"], ["id"])
    op.drop_constraint("chzzk_vod_chat_analytics_chzzk_vod_id_fkey", "chzzk_vod_chat_analytics", type_="foreignkey")
    op.create_foreign_key(
        op.f("chzzk_vod_chat_analytics_chzzk_vod_id_fkey"),
        "chzzk_vod_chat_analytics",
        "chzzk_vods",
        ["chzzk_vod_id"],
        ["id"],
    )
    op.drop_constraint("chzzk_vod_asr_analytics_chzzk_vod_id_fkey", "chzzk_vod_asr_analytics", type_="foreignkey")
    op.create_foreign_key(
        op.f("chzzk_vod_asr_analytics_chzzk_vod_id_fkey"),
        "chzzk_vod_asr_analytics",
        "chzzk_vods",
        ["chzzk_vod_id"],
        ["id"],
    )
    op.drop_constraint("chzzk_channels_channel_id_fkey", "chzzk_channels", type_="foreignkey")
    op.create_foreign_key(op.f("chzzk_channels_channel_id_fkey"), "chzzk_channels", "channels", ["channel_id"], ["id"])
    op.drop_constraint("channel_metadatas_channel_id_fkey", "channel_metadatas", type_="foreignkey")
    op.create_foreign_key(
        op.f("channel_metadatas_channel_id_fkey"), "channel_metadatas", "channels", ["channel_id"], ["id"]
    )
    op.drop_constraint("channel_llm_metadatas_channel_id_fkey", "channel_llm_metadatas", type_="foreignkey")
    op.create_foreign_key(
        op.f("channel_llm_metadatas_channel_id_fkey"), "channel_llm_metadatas", "channels", ["channel_id"], ["id"]
    )
    # ### end Alembic commands ###
