"""Add total_chat_count, total_donation_count, total_donation_amount to vods

Revision ID: 4f8a66d34fe9
Revises: 894339690d32
Create Date: 2025-09-25 15:34:49.852089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8a66d34fe9"
down_revision: str | Sequence[str] | None = "894339690d32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chzzk_vods", sa.Column("total_chat_count", sa.Integer(), nullable=True))
    op.add_column("chzzk_vods", sa.Column("total_donation_count", sa.Integer(), nullable=True))
    op.add_column("chzzk_vods", sa.Column("total_donation_amount", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chzzk_vods", "total_donation_amount")
    op.drop_column("chzzk_vods", "total_donation_count")
    op.drop_column("chzzk_vods", "total_chat_count")
