"""Create initial tables

Revision ID: 87aa2d17a45e
Revises:
Create Date: 2025-09-23 17:54:26.111435

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chatzzk.packages.schemas.db_models import StringAsInt

# revision identifiers, used by Alembic.
revision: str = "87aa2d17a45e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platforms",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("platform_code", sa.String(length=50), nullable=False),
        sa.Column("platform_name", sa.String(length=100), nullable=False),
        sa.Column("donation_unit", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_code"),
    )
    op.create_table(
        "chzzk_channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("platform_id", sa.SmallInteger(), nullable=False),
        sa.Column("channel_id", sa.String(length=255), nullable=False),
        sa.Column("channel_name", sa.String(length=255), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("allow_data_collection", sa.Boolean(), nullable=True),
        sa.Column("is_exposure_default", sa.Boolean(), nullable=True),
        sa.Column("allow_detailed_stats", sa.Boolean(), nullable=True),
        sa.Column("channel_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_vod_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chzzk_channels_allow_data_collection"), "chzzk_channels", ["allow_data_collection"], unique=False
    )
    op.create_index(op.f("ix_chzzk_channels_channel_id"), "chzzk_channels", ["channel_id"], unique=True)
    op.create_index(op.f("ix_chzzk_channels_platform_id"), "chzzk_channels", ["platform_id"], unique=False)
    op.create_table(
        "chzzk_vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("video_no", StringAsInt(), nullable=False),
        sa.Column("video_title", sa.String(length=500), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("video_category_value", sa.String(length=100), nullable=True),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("live_open_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channel_pk", sa.BigInteger(), nullable=False),
        sa.Column(
            "process_status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vod_process_status_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("status_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["channel_pk"], ["chzzk_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chzzk_vods_process_status"), "chzzk_vods", ["process_status"], unique=False)
    op.create_index(op.f("ix_chzzk_vods_video_no"), "chzzk_vods", ["video_no"], unique=True)
    op.create_table(
        "chzzk_asr_entries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_ms", sa.BigInteger(), nullable=False),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("vod_pk", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["vod_pk"], ["chzzk_vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chzzk_asr_entries_timestamp_ms"), "chzzk_asr_entries", ["timestamp_ms"], unique=False)
    op.create_table(
        "chzzk_chat_entries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("os_type", sa.Enum("IOS", "PC", "AOS", name="os_type_enum", native_enum=False), nullable=True),
        sa.Column("pay_amount", sa.Integer(), nullable=True),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column(
            "user_role_code",
            sa.Enum(
                "COMMON_USER",
                "STREAMING_CHAT_MANAGER",
                "STREAMING_CHANNEL_OWNER",
                "STREAMING_CHANNEL_MANAGER",
                name="user_role_code_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "subscription_tier",
            sa.Enum("NO_SUBSCRIPTION", "GENERAL", "PREMIUM", name="subscription_tier_enum", native_enum=False),
            nullable=True,
        ),
        sa.Column("subscription_accumulative_month", sa.Integer(), nullable=True),
        sa.Column(
            "message_type_code",
            sa.Enum("CHAT", "DONATION", "SYSTEM", name="chzzk_message_type_code_enum", native_enum=False),
            nullable=True,
        ),
        sa.Column("user_id_hash", sa.String(length=255), nullable=True),
        sa.Column("vod_pk", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["vod_pk"], ["chzzk_vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chzzk_chat_entries_timestamp_ms"), "chzzk_chat_entries", ["timestamp_ms"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chzzk_chat_entries_timestamp_ms"), table_name="chzzk_chat_entries")
    op.drop_table("chzzk_chat_entries")
    op.drop_index(op.f("ix_chzzk_asr_entries_timestamp_ms"), table_name="chzzk_asr_entries")
    op.drop_table("chzzk_asr_entries")
    op.drop_index(op.f("ix_chzzk_vods_video_no"), table_name="chzzk_vods")
    op.drop_index(op.f("ix_chzzk_vods_process_status"), table_name="chzzk_vods")
    op.drop_table("chzzk_vods")
    op.drop_index(op.f("ix_chzzk_channels_platform_id"), table_name="chzzk_channels")
    op.drop_index(op.f("ix_chzzk_channels_channel_id"), table_name="chzzk_channels")
    op.drop_index(op.f("ix_chzzk_channels_allow_data_collection"), table_name="chzzk_channels")
    op.drop_table("chzzk_channels")
    op.drop_table("platforms")
    # ### end Alembic commands ###
