"""initial_migration_from_current_orm

Revision ID: a4895baa33b2
Revises:
Create Date: 2025-10-20 17:52:29.987415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chatzzk.packages.schemas.orm.models import StringAsInt

# revision identifiers, used by Alembic.
revision: str = "a4895baa33b2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platforms",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("platform_code", sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode"), nullable=False),
        sa.Column("platform_name", sa.String(length=100), nullable=False),
        sa.Column("donation_unit", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_code"),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("platform_id", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_vod_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_platform_id"), "channels", ["platform_id"], unique=False)
    op.create_table(
        "channel_llm_metadatas",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "metadata_description",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "chzzk_channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_channel_id", sa.String(length=100), nullable=False),
        sa.Column("channel_name", sa.String(length=100), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("platform_channel_id"),
    )
    op.create_table(
        "vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vods_channel_id"), "vods", ["channel_id"], unique=False)
    op.create_table(
        "chzzk_vod_asr_analytics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column("total_speech_time_ms", sa.BigInteger(), nullable=False),
        sa.Column("avg_speech_time_per_minute", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    op.create_table(
        "chzzk_vod_chat_analytics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column("total_chat_count", sa.Integer(), nullable=False),
        sa.Column("chat_os_type_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chat_participant_count", sa.Integer(), nullable=False),
        sa.Column("chat_participant_chat_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chat_count_by_subscription", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hidden_chat_count", sa.Integer(), nullable=False),
        sa.Column("avg_chat_count_per_minute", sa.Float(), nullable=False),
        sa.Column("total_donation_count", sa.Integer(), nullable=False),
        sa.Column("total_donation_amount", sa.Float(), nullable=False),
        sa.Column("donor_count", sa.Integer(), nullable=False),
        sa.Column("anonymous_donation_amount", sa.Float(), nullable=False),
        sa.Column("anonymous_donation_count", sa.Integer(), nullable=False),
        sa.Column("avg_donation_amount", sa.Float(), nullable=False),
        sa.Column("avg_donation_count_per_minute", sa.Float(), nullable=False),
        sa.Column("mission_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    op.create_table(
        "chzzk_vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column("video_no", StringAsInt(), nullable=False),
        sa.Column("video_title", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("video_category_value", sa.String(length=100), nullable=True),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("live_open_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_no"),
        sa.UniqueConstraint("vod_id"),
    )
    op.create_table(
        "result_object_keys",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("CHAT_ENTRIES", "ASR_ENTRIES", "SUMMARIES", "META_SUMMARIES", name="resultobjectfiletype"),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id", "file_type", name="uq_vod_id_file_type"),
    )
    op.create_table(
        "vod_overall_processing_statuses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "PERMANENTLY_FAILED", name="vodprocessstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    op.create_table(
        "vod_processing_status_details",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column("status_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vod_processing_status_details")
    op.drop_table("vod_overall_processing_statuses")
    op.drop_table("result_object_keys")
    op.drop_table("chzzk_vods")
    op.drop_table("chzzk_vod_chat_analytics")
    op.drop_table("chzzk_vod_asr_analytics")
    op.drop_index(op.f("ix_vods_channel_id"), table_name="vods")
    op.drop_table("vods")
    op.drop_table("chzzk_channels")
    op.drop_table("channel_llm_metadatas")
    op.drop_index(op.f("ix_channels_platform_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_table("platforms")
    # ### end Alembic commands ###
