"""change jsonb to MutableDict Jsonb

Revision ID: c9061d007f44
Revises: 3aa7659c0135
Create Date: 2025-11-12 17:30:13.586343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9061d007f44"
down_revision: str | Sequence[str] | None = "3aa7659c0135"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chzzk_vod_asr_analytics",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chzzk_vod_asr_analytics",
        "chzzk_vod_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "chzzk_vod_chat_analytics",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chzzk_vod_chat_analytics",
        "chzzk_vod_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "chzzk_vods",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('chzzk_vods_id_seq'::regclass)"),
    )
    op.alter_column("chzzk_vods", "vod_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    op.alter_column(
        "platforms",
        "platform_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "platforms",
        "donation_unit",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "result_object_keys",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "result_object_keys", "vod_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    op.alter_column(
        "vod_overall_processing_statuses",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "vod_overall_processing_statuses",
        "vod_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "vod_processing_status_details",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "vod_processing_status_details",
        "vod_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "vods",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('vods_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vods",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('vods_id_seq'::regclass)"),
    )
    op.alter_column(
        "vod_processing_status_details",
        "vod_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "vod_processing_status_details",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "vod_overall_processing_statuses",
        "vod_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "vod_overall_processing_statuses",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "result_object_keys", "vod_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column(
        "result_object_keys",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "platforms",
        "donation_unit",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "platforms",
        "platform_name",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column("chzzk_vods", "vod_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column(
        "chzzk_vods",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('chzzk_vods_id_seq'::regclass)"),
    )
    op.alter_column(
        "chzzk_vod_chat_analytics",
        "chzzk_vod_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "chzzk_vod_chat_analytics",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chzzk_vod_asr_analytics",
        "chzzk_vod_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "chzzk_vod_asr_analytics",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
