"""refactor vod status and separate pipeline logs

Revision ID: 286b2b592466
Revises:
Create Date: 2025-12-15 18:35:40.525729

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "286b2b592466"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform_code", sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode"), nullable=False),
        sa.Column("platform_url", sa.String(length=512), nullable=False),
        sa.Column("platform_name", sa.String(length=256), nullable=False),
        sa.Column("donation_unit", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_code"),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("platform_channel_id", sa.String(length=256), nullable=False),
        sa.Column("channel_name", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_vod_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_id", "platform_channel_id", name="uq_channel_platform_identifier"),
    )
    op.create_table(
        "channel_llm_contexts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "llm_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name="channel_llm_contexts_channel_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("video_no", sa.String(length=256), nullable=False),
        sa.Column("video_title", sa.String(length=256), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column(
            "pipeline_status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodpipelinestatus"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], name="vods_channel_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "video_no", name="uq_vod_channel_video"),
    )
    op.create_table(
        "vod_pipeline_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "process_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], name="vod_pipeline_logs_vod_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vod_pipeline_logs")
    op.drop_table("vods")
    op.drop_table("channel_llm_contexts")
    op.drop_table("channels")
    op.drop_table("platforms")
    # ### end Alembic commands ###
