"""add index in vods, channels

Revision ID: 34492ccc6f79
Revises: 286b2b592466
Create Date: 2025-12-15 19:17:17.972116

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34492ccc6f79"
down_revision: str | Sequence[str] | None = "286b2b592466"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_channels_platform_channel_id"), "channels", ["platform_channel_id"], unique=False)
    op.create_index(op.f("ix_vods_video_no"), "vods", ["video_no"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vods_video_no"), table_name="vods")
    op.drop_index(op.f("ix_channels_platform_channel_id"), table_name="channels")
    # ### end Alembic commands ###
