"""refactor: Add User, replace is_active with policies

Revision ID: 396250ec19ea
Revises: 18a0123d673a
Create Date: 2025-12-26 17:49:24.162079

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "396250ec19ea"
down_revision: str | Sequence[str] | None = "18a0123d673a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supabase_uid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_supabase_uid"), "users", ["supabase_uid"], unique=True)
    op.add_column("channels", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("channels", sa.Column("is_collection_enabled", sa.Boolean(), server_default="true", nullable=False))
    op.add_column(
        "channels", sa.Column("vod_exposure_delay_hours", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    op.create_foreign_key("channels_user_id_fkey", "channels", "users", ["user_id"], ["id"])
    op.execute("UPDATE channels SET is_collection_enabled = is_active")
    op.drop_column("channels", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels",
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.execute("UPDATE channels SET is_active = is_collection_enabled")
    op.alter_column("channels", "is_active", nullable=False)
    op.drop_constraint("channels_user_id_fkey", "channels", type_="foreignkey")
    op.drop_column("channels", "vod_exposure_delay_hours")
    op.drop_column("channels", "is_collection_enabled")
    op.drop_column("channels", "user_id")
    op.drop_index(op.f("ix_users_supabase_uid"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
