"""init tables

Revision ID: 7ee1762b05c2
Revises:
Create Date: 2025-12-10 22:40:30.027528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ee1762b05c2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodprocessingstatus").create(op.get_bind())
    sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode").create(op.get_bind())
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "platform_code",
            postgresql.ENUM("CHZZK", "YOUTUBE", "SOOP", name="platformcode", create_type=False),
            nullable=False,
        ),
        sa.Column("platform_url", sa.String(length=512), nullable=False),
        sa.Column("platform_name", sa.String(length=256), nullable=False),
        sa.Column("donation_unit", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_code"),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("platform_channel_id", sa.String(length=256), nullable=False),
        sa.Column("channel_name", sa.String(length=256), nullable=False),
        sa.Column("channel_url", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_vod_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_url"),
        sa.UniqueConstraint("platform_id", "platform_channel_id", name="uq_channel_platform_identifier"),
    )
    op.create_table(
        "channel_llm_contexts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "llm_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name="channel_llm_contexts_channel_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "chzzk_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("verified_mark", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name="chzzk_channels_channel_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("video_no", sa.String(length=256), nullable=False),
        sa.Column("video_title", sa.String(length=256), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vod_url", sa.String(length=512), nullable=False),
        sa.Column("detail_chunk_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], name="vods_channel_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "video_no", name="uq_vod_channel_video"),
    )
    op.create_table(
        "vod_processing_statuses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodprocessingstatus", create_type=False
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "status_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["vod_id"], ["vods.id"], name="vod_processing_statuses_vod_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vod_processing_statuses")
    op.drop_table("vods")
    op.drop_table("chzzk_channels")
    op.drop_table("channel_llm_contexts")
    op.drop_table("channels")
    op.drop_table("platforms")
    sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode").drop(op.get_bind())
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodprocessingstatus").drop(op.get_bind())
    # ### end Alembic commands ###
