"""init_schema

Revision ID: 89b8bb695807
Revises:
Create Date: 2026-01-23 11:19:30.075837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89b8bb695807"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodpipelinestatus").create(op.get_bind())
    sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode").create(op.get_bind())
    sa.Enum("ADMIN", "OWNER", "EDITOR", "USER", name="userrole").create(op.get_bind())
    op.create_table(
        "platforms",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "platform_code",
            postgresql.ENUM("CHZZK", "YOUTUBE", "SOOP", name="platformcode", create_type=False),
            nullable=False,
        ),
        sa.Column("platform_url", sa.Text(), nullable=False),
        sa.Column("platform_name", sa.Text(), nullable=False),
        sa.Column("donation_unit", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform_code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("supabase_uid", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.Text(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "OWNER", "EDITOR", "USER", name="userrole", create_type=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "char_length(user_name) >= 4 AND char_length(user_name) <= 20 AND user_name ~ '^[a-z0-9]+$'",
            name="check_user_name_format",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supabase_uid"),
        sa.UniqueConstraint("user_name"),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("editor_id", sa.BigInteger(), nullable=True),
        sa.Column("platform_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_channel_id", sa.Text(), nullable=False),
        sa.Column("channel_name", sa.Text(), nullable=False),
        sa.Column("last_vod_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_collection_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("vod_exposure_delay_hours", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vod_detail_exposure_delay_hours", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["editor_id"], ["users.id"], name="channels_editor_id_fkey"),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="channels_user_id_fkey"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("editor_id"),
        sa.UniqueConstraint("platform_id", "platform_channel_id", name="uq_channel_platform_identifier"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_channels_channel_name"), "channels", ["channel_name"], unique=False)
    op.create_index(op.f("ix_channels_platform_channel_id"), "channels", ["platform_channel_id"], unique=False)
    op.create_table(
        "channel_metadata",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name="channel_metadata_channel_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "vods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("video_no", sa.Text(), nullable=False),
        sa.Column("video_title", sa.Text(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "pipeline_status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodpipelinestatus", create_type=False
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("is_exposed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], name="vods_channel_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "video_no", name="uq_vod_channel_video"),
    )
    op.create_index("idx_vod_exposed_publish", "vods", ["is_exposed", "publish_date"], unique=False)
    op.create_index("idx_vod_status_created", "vods", ["pipeline_status", "publish_date"], unique=False)
    op.create_index(op.f("ix_vods_video_no"), "vods", ["video_no"], unique=False)
    op.create_table(
        "vod_pipeline_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vod_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "process_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vod_id"], ["vods.id"], name="vod_pipeline_logs_vod_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vod_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vod_pipeline_logs")
    op.drop_index(op.f("ix_vods_video_no"), table_name="vods")
    op.drop_index("idx_vod_status_created", table_name="vods")
    op.drop_index("idx_vod_exposed_publish", table_name="vods")
    op.drop_table("vods")
    op.drop_table("channel_metadata")
    op.drop_index(op.f("ix_channels_platform_channel_id"), table_name="channels")
    op.drop_index(op.f("ix_channels_channel_name"), table_name="channels")
    op.drop_table("channels")
    op.drop_table("users")
    op.drop_table("platforms")
    sa.Enum("ADMIN", "OWNER", "EDITOR", "USER", name="userrole").drop(op.get_bind())
    sa.Enum("CHZZK", "YOUTUBE", "SOOP", name="platformcode").drop(op.get_bind())
    sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="vodpipelinestatus").drop(op.get_bind())
    # ### end Alembic commands ###
