"""add index for vod queue optimization

Revision ID: 957cb841ff5a
Revises: 396250ec19ea
Create Date: 2025-12-28 18:27:21.695037

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "957cb841ff5a"
down_revision: str | Sequence[str] | None = "396250ec19ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_vod_exposed_publish", "vods", ["is_exposed", "publish_date"], unique=False)
    op.create_index("idx_vod_status_created", "vods", ["pipeline_status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_vod_status_created", table_name="vods")
    op.drop_index("idx_vod_exposed_publish", table_name="vods")
    # ### end Alembic commands ###
