"""add is_exposed in VOD

Revision ID: efa0d3012a67
Revises: 34492ccc6f79
Create Date: 2025-12-22 21:12:39.359500

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efa0d3012a67"
down_revision: str | Sequence[str] | None = "34492ccc6f79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vods", sa.Column("is_exposed", sa.Boolean(), server_default="true", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vods", "is_exposed")
    # ### end Alembic commands ###
