import { ChannelCardUI } from "../types";

export const MOCK_CHANNEL_DATA: ChannelCardUI[] = [
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
];
