import { ChannelUI } from "../types";

export const MOCK_CHANNEL_DATA: ChannelUI[] = [
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official1",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official2",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official3",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official4",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official5",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official6",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official7",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official8",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official9",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official11",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official12",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official13",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official14",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official15",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official16",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official17",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "배도라지",
        platform: "youtube",
        channelId: "baedoraji123",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official18",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        channelId: "chzzk_official19",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
];
