import { ChannelCardUI } from "../types";

export const MOCK_CHANNEL_DATA: ChannelCardUI[] = [
    {
        id: 1,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 2,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 11,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 21,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 12,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 22,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 13,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 23,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 14,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 24,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 15,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 25,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 16,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 26,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 122,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 233,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 122555,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 244,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 144,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 255,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 166,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 267,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 1321,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 2444,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 1521,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 26664,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 1123,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 253453,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 142424,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 233434,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 155555555,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 2334341444,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 199,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 29,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 10,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 2889,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 198,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 2970,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 107,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 207,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 108,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 208,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 100,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 200,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 881,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 7652,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 4561,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 54352,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 63671,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 76582,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
    {
        id: 68551,
        name: "침착맨",
        profileUrl: "https://placehold.co/100x100/png?text=Chim",
        platformChannelId: "chzzk_official",
        description: "전 이말년 현 침착맨입니다.",
        platform: "chzzk",
    },
    {
        id: 765752,
        name: "배도라지",
        platform: "youtube",
        platformChannelId: "baedoraji123",
    },
];
