model_list:
  - model_name: segment_summarize
    litellm_params:
      model: gemini/gemini-2.0-flash
      temperature: 0.2

  - model_name: chapter_summarize
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      temperature: 0.2


litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

router_settings:
  num_retries: 5
  retry_after: 10
