services:
  test-db:
    image: postgres
    container_name: chatzzk-test-db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pw
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test-adminer:
    image: adminer
    ports:
      - 8080:8080

  asr-inference-server:
    image: test-asr-server
    ports:
      - 8000:8000
    volumes:
      - test-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  llm-proxy-server:
    image: llm-proxy-server
    ports:
      - "4000:4000"
    environment:
      - GEMINI_API_KEY=AIzaSyBhHpg1tm3n1t9QFuIce4Z5C_srJ901kdc
      - GEMINI_API_KEY_PAID=AIzaSyCAA7f7MiqIhUmvG_tYPaGypaLzBIVo454
      - LANGFUSE_PUBLIC_KEY=pk-lf-dc84fc6b-d660-4a82-845d-130e213752b2
      - LANGFUSE_SECRET_KEY=sk-lf-90b7fb4d-f5bf-498a-bf16-c3fa02a992a0

volumes:
  test-db-data:
  test-minio-data:
  test-models:
