services:
  chatzzk-collector-dev:
    image: chatzzk/chatzzk-collector-dev
    build:
      context: .
      dockerfile: app/pipeline/Dockerfile
    command: prefect worker start --pool "process-pool-dev"
    depends_on:
      - asr-inference-server-dev
      - llm-proxy-server-dev
    env_file:
      - dev.env
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - dev-samples:/app/samples-dev
    networks:
      - default # ASR, LLM과 통신
      - pipeline-shared-network # Prefect Server와 통신
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 24/7 구동 시 예상치 못한 종료 대비
    restart: unless-stopped

  asr-inference-server-dev:
    image: chatzzk/asr-inference-server-dev
    build:
      context: .
      dockerfile: app/servers/asr_inference_server/Dockerfile
    command: gunicorn app.servers.asr_inference_server.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 120
    ports:
      - 8000:8000 # 로컬 수행 용
    volumes:
      - dev-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  llm-proxy-server-dev:
    image: chatzzk/llm-proxy-server-dev
    build:
      context: .
      dockerfile: app/servers/llm_proxy_server/Dockerfile
    ports:
      - "4000:4000" # 로컬 수행 용
    env_file:
      - dev.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
networks:
  pipeline-shared-network:
    external: true

volumes:
  dev-models:
  dev-samples:
