[project]
name = "chatzzk-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]

db-migration = [
    "chatzzk-schemas[orm]",
    "alembic>=1.17.2",
    "alembic-postgresql-enum>=1.8.0",
    "psycopg2-binary>=2.9.11",
]

dev = [
    "chatzzk-collector[db-migration]",
    "pre-commit>=4.4.0",
    "ruff>=0.14.5",
]

[tool.uv.sources]
"chatzzk-schemas" = { workspace = true }
"chatzzk-constants" = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/*",
]

[tool.ruff]
line-length = 120
target-version = "py311"
