FROM redis:latest

# 커스텀 redis.conf가 있다면 복사
# COPY ./redis.conf /usr/local/etc/redis/redis.conf

# Redis 실행 (기본 설정 또는 커스텀 설정 사용 시 아래 주석 해제)
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
CMD ["redis-server"]
